services:

  app:
    build:
      context: ../..
      dockerfile: deploy/local/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env.local  
    volumes:
      - ../../backend/app/data:/app/data
    depends_on: []
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
    name: delivery_system_mysql_data