services:
  app:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: teckwah-tms
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    restart: "no"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=delivery_system
