version: '3.8'

services:
  # Node.js 애플리케이션
  app:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: teckwah-node-app
    ports:
      - '8000:8000'
    env_file:
      - ./deploy/.env
    restart: always
    volumes:
      - ./logs:/app/logs
    extra_hosts:
      - 'host.docker.internal:host-gateway'
