version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: teckwah-tms
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env