version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: teckwah-node-app
    ports:
      - '8000:8000'
    env_file:
      - ./deploy/.env
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
