version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: teckwahkr-tms
    restart: 'no'
    ports:
      - '8080:8080'
    env_file:
      - .env
