# deploy/docker-compose.yml
services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        BUILD_MODE: production
    ports:
      - '8000:8000'
    environment:
      - API_BASE_URL=http://0.0.0.0:8000
      - LOG_LEVEL=DEBUG
      - DEBUG=True
      - MYSQL_HOST=host.docker.internal
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.local
    volumes:
      - ./logs:/app/logs
    networks:
      - app_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'no'
    container_name: teckwah-app

networks:
  app_network:
    driver: bridge
